services:
  postgresql:
    container_name: saga-postgres
    image: postgres:15.4-bullseye
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: "45140450"
      POSTGRES_DB: saga_db
      POSTGRES_USER: carlos
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U carlos -d saga_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
